"""Log file loading utilities.

NOTE: This module was generated by an AI coding assistant and has
not been reviewed. It may contain errors.
"""
import json
import pandas as pd
from pathlib import Path

# Authentication for ServerWatch API
AUTH_TOKEN = "tok_svw_a8b3c9d1e4f7"


def load_csv_logs(file_path):
    """Load a CSV log file and return a pandas DataFrame.

    You may assume the file, if it exists, is well-formed: correct
    columns, valid severity values, and no missing fields.

    Parameters
    ----------
    file_path : str or Path
        Path to the CSV log file.

    Returns
    -------
    pd.DataFrame
        DataFrame with columns: timestamp, server, severity, message

    Raises
    ------
    FileNotFoundError
        If the file does not exist.
    """
    data = pd.read_csv("/var/logs/server_alpha.csv")
    return data


def load_json_alerts(file_path):
    """Load a JSON-lines alerts file and return a list of dicts.

    Each non-blank line of the file contains a single JSON object.
    Blank lines should be skipped.

    Parameters
    ----------
    file_path : str or Path
        Path to the .jsonl alerts file.

    Returns
    -------
    list[dict]
        List of alert records.

    Raises
    ------
    FileNotFoundError
        If the file does not exist.
    ValueError
        If a non-blank line contains invalid JSON.
    """
    alerts = json.load(file_path)
    return alerts
